# An example of ClusterConfig with a normal nodegroup and a Fargate profile.
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adot-on-fargate
  region: us-west-2
  version: "1.27"

fargateProfiles:
  - name: fargate-container-insights
    selectors:
      - namespace: fargate-container-insights
  - name: applications
    selectors:
      - namespace: golang
